name:
  binomial: macrolepiota procera
  common: parasol
  distribution: @europe, @northamerica
features: @cap, @step, @gills
notes:
  - title: Summary
    notes: grows in grass, is fairly tall
  - title: Warning
    notes: In North America, there is a gren-gilled variety that is somewhat toxic.
links:
- https://www.youtube.com/watch?v=xK87iMP4GMI
images:
- link1
- link2 ...

stages:
- name: developing
  sources:
  - @source/rogerp-m ; page 124
  basics:
    cap: @clr/white, @tx/scaly
    gills: @gil/adnate, @gil/crowded, @clr/white, @clr/cream
    stem: @firm, @clr/white, @tx/scaly
    ecology: @saprot
    spores: n/a
  images: ...
  confusions:
    - name: young death cap
      ref:  ./death-cap#young # reference a local file, and a specific stage
    - name: young amanitas in general
      ref: @@amanita # list all specimens that use this alias

- name: full
  sources:
  - @rogerp-m  ; page 124
  basics:
    cap: @clr/white, @tx/scaly
    gills: @gil/adnate, @gil/crowded, @clr/white, @clr/cream
    stem: @firm, @clr/white, @tx/scaly
    ecology: @saprot
    spores: n/a
  images: ...
  confusions:
    - name: green-gilled parasol
      ref: https://... # URI
    - name: slender parasol
      ref: ./slender-parasol # './': file name, without extension
